version: '3.8'
services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

